# Generated by Django 2.2.6 on 2019-12-21 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='changed_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
